# Generated by Django 3.1.5 on 2021-02-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Null', max_length=64)),
                ('position', models.CharField(default='Null', max_length=64)),
                ('date', models.DateField(blank=True, default='', null=True)),
                ('desc', models.TextField(default='Null', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Null', max_length=32)),
                ('birthday', models.DateField(blank=True, default='', null=True)),
                ('city', models.CharField(default='Null', max_length=32)),
                ('email', models.EmailField(default='user@gmail.com', max_length=254)),
                ('aboutme', models.TextField(default='Null', max_length=255)),
                ('major', models.CharField(default='Null', max_length=32)),
                ('userinfo', models.OneToOneField(default='Null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default='Null', max_length=64)),
                ('degree', models.CharField(default='Null', max_length=64)),
                ('date', models.DateField(blank=True, default='', null=True)),
                ('desc', models.TextField(default='Null', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectionid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('userid', models.ManyToManyField(related_name='userid_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
