# Generated by Django 3.1.5 on 2021-02-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Null', max_length=32)),
                ('lanuch_date', models.DateField(blank=True, default='', null=True)),
                ('city', models.CharField(default='Null', max_length=32)),
                ('email', models.EmailField(default='user@gmail.com', max_length=254)),
                ('aboutcompany', models.TextField(default='Null', max_length=255)),
                ('industry', models.CharField(default='Null', max_length=32)),
                ('num_emp', models.IntegerField()),
                ('company_id', models.OneToOneField(default='Null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Null', max_length=64)),
                ('location', models.CharField(default='Null', max_length=64)),
                ('date', models.DateTimeField(blank=True, default='', null=True)),
                ('desc', models.TextField(default='Null', max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
